### ISSUE TITLE
Error when creating multiple codedeploy applications

### ISSUE THREAD

**Issue by yamasaki760** [skyscrapers/terraform-codedeploy#11]
I'm trying to create multiple codedeploy applications within a simple main.tf

The problem I'm running into is that each codedeploy application I create in my configuration implicitly tries to create an s3 aws_iam_policy.codedeploy_policy with a hardcoded name (s3_bucket_access).

My _terraform apply_ fails, complaining that the resource already exists.  

Could we add a ${var.name_prefix} to the policy, or,  some other way to point additional codedeploy configurations to the already-created s3 bucket policy?   

i.e. (s3bucket/main.tf) 

` resource "aws_iam_policy" "codedeploy_policy" {
    name = "${var.name_prefix}_codedeploy_s3_access"
`

This is what I've done locally, and, aside from having multiple identical policies (1 per app), seems to work fine.

Thanks in advance.

Regards,

Edwin

**Comment by iuriaranda** [comment]
Hi @yamasaki760 , first of all, I apologize for the late reply.

This becomes a problem only if you want to create multiple S3 buckets, which I guess it's what you need. But just to clarify, you could have multiple CodeDeploy applications and deployment groups sharing the same S3 bucket, which is our use-case and that's why we didn't notice the issue in the first place.

In any case, your suggestion looks good. Having a resource with a fixed name is indeed not a good practice, our mistake.
I'm going to merge the suggested change from @SevereOverfl0w's fork.
